// Code generated by "stringer -type=logSource -linecomment"; DO NOT EDIT.

package backgroundcat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[MultiMC-1]
	_ = x[VanillaLauncher-2]
}

const _logSource_name = "UnknownMultiMCthe vanilla launcher"

var _logSource_index = [...]uint8{0, 7, 14, 34}

func (i logSource) String() string {
	if i < 0 || i >= logSource(len(_logSource_index)-1) {
		return "logSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _logSource_name[_logSource_index[i]:_logSource_index[i+1]]
}
