/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.fabricmc.bot

// import com.kotlindiscord.kord.extensions.ExtensibleBot

/** @suppress **/
fun main() {
//    val bot = ExtensibleBot()
}
