/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.fabricmc.bot

import com.gitlab.kordlib.gateway.Intents
import com.gitlab.kordlib.gateway.PrivilegedIntent
import com.kotlindiscord.kord.extensions.ExtensibleBot
import mu.KotlinLogging
import net.fabricmc.bot.conf.buildInfo
import net.fabricmc.bot.conf.config
import net.fabricmc.bot.database.Migrator
import net.fabricmc.bot.extensions.*

/** The current instance of the bot. **/
val bot = ExtensibleBot(
        prefix = config.prefix,
        token = config.token,

        guildsToFill = listOf(config.guildSnowflake),
        fillPresences = true
)

/**
 * The main function. Every story has a beginning!
 */
@OptIn(PrivilegedIntent::class)
suspend fun main() {
    val logger = KotlinLogging.logger {}

    logger.info { "Starting Fabric Discord Bot, version ${buildInfo.version}." }

    Migrator.migrate()

    bot.addExtension(ActionLogExtension::class)
    bot.addExtension(CleanExtension::class)
    bot.addExtension(DefconExtension::class)
    bot.addExtension(EmojiExtension::class)
    bot.addExtension(FilterExtension::class)
    bot.addExtension(GitHubExtension::class)
    bot.addExtension(InfractionsExtension::class)
    bot.addExtension(LoggingExtension::class)
    bot.addExtension(MappingsExtension::class)
    bot.addExtension(ModerationExtension::class)
    bot.addExtension(SelfRoleExtension::class)
    bot.addExtension(SyncExtension::class)
    bot.addExtension(TagsExtension::class)
    bot.addExtension(UtilsExtension::class)
    bot.addExtension(VersionCheckExtension::class)

    bot.start(
            presenceBuilder = {
                playing("${config.prefix}help for command help")
            },

            intents = {
                +Intents.all
            }
    )
}
